#:schema node_modules/wrangler/config-schema.json
name = "discourse-calendar-ical-generator"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

route = { pattern = "feed.underline.center", zone_name = "underline.center" }

# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
